### ISSUE TITLE
How to show versions in the dependency chains?

### ISSUE THREAD

**Issue by MoSattler** [Helcaraxan/gomod#119]
Hi! Great project - this is helping a bunch! Many thanks!

I got one question though.
I saw [here](https://github.com/Helcaraxan/gomod#dependency-chains) that you can generate images that include the dependency versions. 
If I am running
```
gomod graph 'rdeps(github.com/some/gopackage)' | dot -T png -o DocName.png
```

I do not get the versions though, but just the package names. Is there a flag I need to set?

**Comment by a-johanes** [comment]
it is possible to generate the version, you need to check the help command for the `graph` module
```
gomod graph --help
```

in there it says that you could add the version by enabling the annotation flag
```
gomod graph '**' --annotation
```

**Comment by MoSattler** [comment]
Thanks!
