### ISSUE TITLE
Readme improvement: Mention that `dot` tool means  graphviz

### ISSUE THREAD

**Issue by tomor** [Helcaraxan/gomod#13]
It would be great to add a link to *graphviz* or at least mention that `dot` tool means *graphviz* in the readme.

**Why:**
The `gomod` error says this: 
ERRO[0000] The "dot" tool dependency does not seem to be available. Please install it first. 
Error: missing tool dependencies

And when you go to README it doesn't explain what `dot` tool is and you need to google it.

**Comment by Helcaraxan** [comment]
Closed via #14.
