### ISSUE TITLE
read GOPROXY from go env or env

### ISSUE THREAD

**Issue by dfang** [Helcaraxan/gomod#70]
```
$ gomod analyse
ERRO[0005] No connectivity.                              error="failed to ping https://proxy.golang.org/: Get https://proxy.golang.org/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
Error: failed to ping https://proxy.golang.org/: Get https://proxy.golang.org/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Usage:
  gomod analyse [flags]

Aliases:
  analyse, analyze

Flags:
  -h, --help   help for analyse

Global Flags:
  -q, --quiet     Silence output from go tool invocations
  -v, --verbose   Verbose output
```

# Feature request

## Checklist

- [ ] The feature / improvement you are suggesting overlaps with the purpose of `gomod`:
      facilitating the management of Go modules and their dependencies.
- [ ] You have examined various alternatives to the new feature / improvement you are suggesting
      and are describing the results in the description below.
- [ ] You have filled in the three sections below and deleted their corresponding placeholders
      texts.

## Description

i'm in china, sometime golang.org is not reachable, so normally i will set GOPROXY to goproxy.cn or export GOPROXY env

```
go env | grep -i goproxy
```

## Implementation suggestions

read from goproxy from go env

**Comment by Helcaraxan** [comment]
Hello @dfang. My apologies for the delay in responding to this issue. It will be fixed in #82 which should land in the next few minutes.
