### ISSUE TITLE
Support printing of package graphs

### ISSUE THREAD

**Issue by Helcaraxan** [Helcaraxan/gomod#71]
# Feature request

## Checklist

- [x] The feature / improvement you are suggesting overlaps with the purpose of `gomod`:
      facilitating the management of Go modules and their dependencies.
- [x] You have examined various alternatives to the new feature / improvement you are suggesting
      and are describing the results in the description below.
- [x] You have filled in the three sections below and deleted their corresponding placeholders
      texts.

## Description

- Although dependency resolution is done at module level the underlying finer-grained package graph has an equal importance. `gomod` should support printing a package graph as well, with packages ideally grouped together on a per-module basis.

## Implementation suggestions

`gomod` is already aware of the package graph so this will likely most be a matter of building the specific visualiation with the existing graph logic and wiring it into the CLI.

## Additional information

More detailed implementation suggestions will be added soon(tm).

**Comment by mvdan** [comment]
The particular use case I have right now: a v0 module is doing some breaking changes in a few APIs, and we want to inspect downstream modules to see how much code they would need to update to adapt to the changes.

Step 1 is finding those modules, which is a difficult problem but can be mostly solved by using GitHub's search.

Step 2 is seeing which of their packages depend on packages of ours which are going to change. This is where we'd like to obtain package import graph data. Ideally trimmed to "graph all the packages which end up importing packages X or Y", but that could always be something we trim ourselves later.

**Comment by Helcaraxan** [comment]
This should now be supported as of #90 and will be part of the soon-to-be 0.6.0 release. Please file any issues you encounter with the new feature as a new ticket!
